/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    'intro-icedq',
    {
      type: 'category',
      label: 'Installing On Premise',
      items: [
        'onprem/requirements',
        'onprem/vm-cluster-install',
        'onprem/existing-cluster-install'
        ]
    },
        {
      type: 'category',
      label: 'Installing On AWS',
      items: [
        'aws/requirements',
        'aws/vm-cluster-install',
        'aws/existing-cluster-install'
        ]
    },
        {
      type: 'category',
      label: 'Installing On Azure',
      items: [
        'azure/requirements',
        'azure/vm-cluster-install',
        'azure/existing-cluster-install'
        ]
    }
  ]
};

module.exports = sidebars;
